var GAME_LEVELS = [
  ["                                                                                ",
   "  xxx                                                                      xxx  ",
   "  x                                             o                          oox  ",
   "  x                                             x                          oox  ",
   "  x @                                           x                          xxx  ",
   "  xxx                                          xxx                           x  ",
   "  x                                    o       xxx                     u     x  ",
   "  x                                           xxxx            xx             x  ",
   "  x                                           xxyx      xxx                  x  ",
   "  x                                           xxxxx                          x  ",
   "  x                      xxx                 xxyxxx              xxx         x  ",
   "  x                   o                      xxxxxx!                         x  ",
   "  x                                  xxx     xxxxyxx!         x        o     x  ",
   "  x                  xy           u          xxyxxxx!                        x  ",
   "  x         o        b         o           xxxxxxyxx!    x                   x  ",
   "  xb             xx               u          xyxyyxx!            b    yyy    x  ",
   "  x                                         xxxyyxxyx!              x     x  x  ",
   "  xxxxx!!!!!x!!!xxxxxxxyxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxx!!!!xxyxxxxxxx!!!!!xxxx  ",
   "       xxxxxxxxx              xxx                      xxxx          xxxxx      ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                  ",
   "  xxxx                                                                                                            ",
   "  x                                                                                                               ",
   "  x @                                                                                                             ",
   "  x                                                                                                               ",
   "  xxx                                                                                                             ",
   "                                                                                                                  ",
   "                                                                                 o                                ",
   "                oo      xxxxx                                    b      xxxx                                      ",
   "                             y                                   xxx                                              ",
   "                xxxx          x          o                                                                        ",
   "                     u         y                                                   xxxx                           ",
   "                                xxxx  x  x  x  x                    x                                             ",
   "                       u                                                                 b                        ",
   "                                                                                         xxx                      ",
   "                        u                                          x                                              ",
   "                                                                                                 o                ",
   "                                                                                                                  ",
   "                      xxxx                                    xyxx                            xyyxyyxxx           ",
   "                                                                                                                  ",
   "                 xyxx                                 xxxyxx                                                  xx  ",
   "                x                                u u                                                           x  ",
   "!          o   x                                                                                               x  ",
   "!             x                              b  u                                                              x  ",
   "!            x                                 o                                                               x  ",
   "!!          x                                xxxx                                                  !        oo x  ",
   "!!!        x                                                 !                                  !!          oo x  ",
   "!!!!      x                                            !!!!                                 !!!!!!!  !    yxxxxx  ",
   "!!!!!!!          !    !!!!!!!!                      !!!!!!!!!   !             !!!!    !  !!!!!!!!!!!!   !         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                            x                 ",
   "                                                                                                              ",
   "                                                                      xxx   xxx            x                  ",
   "                      o   o   o    o                               o      u                                   ",
   "                  u   u   u   u    u                              xxy                    x                    ",
   "                                                                          u                                   ",
   "               u                      b                                                 x                     ",
   "                                      xxxy                                u                               bbb ",
   "                                                                                    xxxx                      ",   "  x  o      u                                                             u                               xxx ",
   "  x                                                                                                         x ",
   "  x                                                                       u                                 x ",
   "  x      u                                                                                                  x ",
   "  x                                         b                       o     u                        u     oo x ",
   "  x@                                                                                                     oo x ",
   "  x                                         xxxx    u    u    u  u  u   u                            yyxxxxxx ",
   "  xxxx                                                                                                        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                             ",
   "     x   x xxxxx x    x      ",
   "      x x  x   x x    x      ",
   "       x   x   x x    x      ",
   "       x   x   x x    x      ",
   "       x   xxxxx  xxxx       ",
   "                             ",
   "      x     x x x   x        ",
   "      x     x x xx  x        ",
   "      x  x  x x x x x        ",
   "       x x x  x x  xx        ",
   "        x x   x x   x        ",
   "                             "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
